// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhU1qsFaL_iz4bbJ9fetyr2FKYEM13K5k',
    appId: '1:509264837027:web:2b3dfd7b5710cbdda84216',
    messagingSenderId: '509264837027',
    projectId: 'internbridge-4b9be',
    authDomain: 'internbridge-4b9be.firebaseapp.com',
    storageBucket: 'internbridge-4b9be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ1EnzzpN91AIYfddsbWXp9SSC_MDcD6E',
    appId: '1:509264837027:android:e3fd20c1cb562208a84216',
    messagingSenderId: '509264837027',
    projectId: 'internbridge-4b9be',
    storageBucket: 'internbridge-4b9be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpp49LR_LAutMmf2C7K2NO9QUf4oDSrPA',
    appId: '1:509264837027:ios:4e9e4c28b5f59bb5a84216',
    messagingSenderId: '509264837027',
    projectId: 'internbridge-4b9be',
    storageBucket: 'internbridge-4b9be.firebasestorage.app',
    iosBundleId: 'com.example.internbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpp49LR_LAutMmf2C7K2NO9QUf4oDSrPA',
    appId: '1:509264837027:ios:4e9e4c28b5f59bb5a84216',
    messagingSenderId: '509264837027',
    projectId: 'internbridge-4b9be',
    storageBucket: 'internbridge-4b9be.firebasestorage.app',
    iosBundleId: 'com.example.internbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhU1qsFaL_iz4bbJ9fetyr2FKYEM13K5k',
    appId: '1:509264837027:web:c121b36ecacf9748a84216',
    messagingSenderId: '509264837027',
    projectId: 'internbridge-4b9be',
    authDomain: 'internbridge-4b9be.firebaseapp.com',
    storageBucket: 'internbridge-4b9be.firebasestorage.app',
  );
}
